nrwl/nx-labs

packages/remix/generators.json
hides the preset generator which is only useful in the create-nx-workspace phase and should not be picked up by - say Nx Console. Same for the "setup" generator.
=> fix(remix): hide non-relevant generators

packages/expo/src/executors/build-ios/schema.d.ts
Well, this was pretty clearly wrong.
=> Fix typo in ExpoBuildIOSOptions type

package.json, scripts/nx-release.mjs, scripts/package.sh, scripts/publish.sh, yarn.lock
This PR converts `nx-release.js` to ESM. This to account for #97 which updated the `release-it` package to `15.2` which uses ESM only. This broke the `nx-release.js` script since it couldn't import the ESM module.
Long-term, we should probably transition this repo to use the same release process as the main Nx repo, but this unblocks us for now.
=> feat(repo): convert nx-release.js to esm

packages/nx-ignore/README.md, packages/nx-ignore/package.json, packages/nx-ignore/src/index.ts
This PR reworks the `nx-ignore` package to ensure Nx is installed in the workspace root, and use that exact version rather than have a dependency on `nx`.
This removes weirdness around how to invoke `print-affected` and potential version mismatches (which can result in invalid paths, etc.).
Also add a `--root` option for debugging purposes, and if Vercel ever change the way things are executed we'd have a workaround.
Once we have a globally runnable `nx` command that does not depend on `node_modules` we can update this package to use that instead.
Fixes #131
=> fix(nx-ignore): re-use Nx CLI installed to workspace rather than have a dependency to it

package.json, packages/nx-ignore/package.json, packages/nx-ignore/src/index.ts
This PR updates the Nx install to a temp location, then move it to the workspace root. This allows Nx install to be found without touching `package.json` and lockfiles.
=> fix(nx-ignore): install Nx to a temp location to avoid touching workspace files

packages/nx-ignore/README.md, packages/nx-ignore/src/index.ts
This PR adds a `--plugins` option to `nx-ignore` so users can specify additional plugins to install that are required for graph extensions. By default, pick up plugins from `nx.json` and install the ones that are found in `package.json`.
If `nx.json` has the following:
```json
{
"plugins" ["@monodon/rust"]
}
```
Then running `npx nx-ignore nx-dev --verbose` in the Nx repo should install that plugin before building project graph.
Output is like this:
```bash
≫ Using Nx to determine if this project (nx-dev) is affected by the commit...
≫ Running from /Users/jack/projects/nx-labs/dist/packages/nx-ignore/src
≫ Workspace root is /Users/jack/projects/nx
≫ Creating temp folder to install Nx: /var/folders/p4/6tvkdn_11xlc_2j999ybhbkr0000gn/T/.nx-ignore
≫ Ignore plugin @monodon/rust (workspace …
```
=> feat(nx-ignore): add support for third-party plugins when building Nx graph

e2e/nx-ignore-e2e/jest.config.js, e2e/nx-ignore-e2e/project.json, e2e/nx-ignore-e2e/tests/nx-ignore.spec.ts, e2e/nx-ignore-e2e/tsconfig.json, e2e/nx-ignore-e2e/tsconfig.spec.json, packages/nx-ignore/README.md, packages/nx-ignore/src/index.ts
This PR adds a check for the commit message to determine if the build should be skipped or forced to build.
Logic is as follows:
```
Skip nx-ignore check and ignore deployment:
- [skip ci]
- [ci skip]
- [no ci]
- [nx skip <app>]
Skip nx-ignore check and force deployment:
- [nx deploy]
- [nx deploy <app>]
```
For example, `git commit -m '[nx deploy] something'` will force all apps to deploy, and `git commit -m [nx skip]` will skip deploys for all apps.
Closes #133
=> feat(nx-ignore): add ability to skip or force deploys from commit message

packages/deno/src/graph/process-graph.ts
all deps where being added as explicit dependencies which causes an issue in nested projects where the nested project will always show an edge to the parent project in the project graph.
=> chore(deno): only add local as explicit deps

packages/deno/src/executors/run/run.impl.ts, packages/deno/src/generators/application/generator.ts, packages/deno/src/generators/library/library.ts, packages/deno/src/generators/utils/add-path.ts
the @nrwl/deno:run executor requires a buildTarget in order to not throw an error about not being able to read 'main' of undefined.
this is because the 'mergedOptions' is not defaulted and is only assigned when a buildTarget is provided. 
instead the mergedOptions should be defaulted to the incoming options and then if there is a buildTarget to combined the resolved build options with the existing defined options passed into @nrwl/deno:run executor.
This PR also fixes an issue where when using nx in a root level project (standalone) the generated paths in the project configurations would contain a '.' for the 'projectRoot'. while technically a valid path, it looks ugly. Now the path is checked to see if the root is a '.' and omits that part of the path if that's the case.
=> fix(deno) buildTarget should not be required for the @nrwl/deno:run executor

packages/deno/src/executors/run/run.impl.ts
When using executors like @nrwl/cypress an initial event needs to be emitted so it knows to continue running, this only applies to watch mode for the executors
=> fix(deno): emit once when running in watch mode

e2e/rspack-e2e/tests/rspack.spec.ts, packages/rspack/generators.json, packages/rspack/package.json, packages/rspack/src/executors/rspack/rspack.impl.ts, packages/rspack/src/generators/application/application.ts, packages/rspack/src/generators/configuration/configuration.ts, packages/rspack/src/generators/configuration/schema.d.ts, packages/rspack/src/generators/configuration/schema.json, packages/rspack/src/index.ts
This PR cleans up the rspack project setup.
- `outputPath` is `dist/<app>` for standalone apps not just `dist` (same as React plugin).
- Clean output before build.
- Generate `development` configuration for `build` and `serve` targets so apps are run in dev-mode when serving.
- Rename `@nrwl/rspack:rspack-project` to `@nrwl/rspack:configuration` to match Vite setup, and removed validation since users can always git reset.
=> feat(rspack): clean-up project setup

e2e/deno-e2e/project.json, e2e/deno-e2e/tests/deno-integrated.spec.ts, e2e/deno-e2e/tests/deno-standalone.spec.ts, packages/deno/README.md, packages/deno/generators.json, packages/deno/src/generators/application/generator.ts, packages/deno/src/generators/application/schema.d.ts, packages/deno/src/generators/application/schema.json, packages/deno/src/generators/preset/generator.ts, packages/deno/src/generators/preset/schema.d.ts, packages/deno/src/generators/preset/schema.json
This PR adds `@nrwl/deno:preset` generator for use with CNW and support standalone projects.
```
npx create-nx-workspace@latest --preset=@nrwl/deno
npx create-nx-workspace@latest --preset=@nrwl/deno --monorepo
```
=> feat(deno): add support for standalone as the default setup

packages/rspack/src/utils/versions.ts
Updating to `0.1.0` as the stable version we're releasing with today.
=> feat(rspack): update and pin rspack to 0.1.0

e2e/deno-e2e/tests/deno-integrated.spec.ts, e2e/deno-e2e/tests/deno-misc.spec.ts, e2e/deno-e2e/tests/deno-standalone.spec.ts, packages/deno/generators.json, packages/deno/src/executors/bundle/bundle.impl.ts, packages/deno/src/executors/lint/lint.impl.ts, packages/deno/src/executors/run/run.impl.ts, packages/deno/src/executors/test/test.impl.ts, packages/deno/src/generators/add-import/generator.ts, packages/deno/src/generators/add-import/schema.d.ts, packages/deno/src/generators/add-import/schema.json, packages/deno/src/generators/application/schema.json, packages/deno/src/generators/init/generator.ts, packages/deno/src/generators/init/schema.json, packages/deno/src/generators/library/files/node.ts__template__, packages/deno/src/generators/library/library.spec.ts, packages/deno/src/generators/library/library.ts, packages/deno/src/generators/library/schema.d.ts, packages/deno/src/generators/library/schema.json, packages/deno/src/generators/preset/generator.ts, packages/deno/src/generators/preset/schema.json, packages/deno/src/generators/utils/add-path.ts, packages/deno/src/generators/utils/imports.spec.ts, packages/deno/src/generators/utils/imports.ts, packages/deno/src/generators/utils/ts-config.ts, packages/deno/src/graph/process-graph.ts, packages/deno/src/utils/run-deno.ts
- check for deno before running and provide helpful error when not found
- add --add-node-entrypoint option to lib generator to create a node.ts for dual runtime libs
- add --import-path option to lib generator to override the generated import path
- add add-import generator to take tsconfig path and add to import_map.json
TODO:
=> feat(deno): QoL improvements for generators

packages/deno/executors.json, packages/deno/package.json, packages/deno/src/executors/emit/emit.impl.ts, packages/deno/src/executors/emit/schema.d.ts, packages/deno/src/executors/emit/schema.json, packages/deno/src/generators/application/__snapshots__/application.spec.ts.snap, packages/deno/src/generators/application/lib.ts, packages/deno/src/generators/setup-serverless/lib/deno-deploy.ts, packages/deno/src/generators/utils/testing/deno-app.ts
Since `deno bundle` is deprecated, add a new `@nrwl/deno:emit` executor that wraps [`deno_emit`](https://github.com/denoland/deno_emit). This is a more basic version of bundle that does not support options such as `--watch`.
Update app generator to use `@nrwl/deno:emit` instead, and add a deprecation message to `@nrwl/deno:bundle`.
=> feat(deno): add @nrwl/deno:emit executor that replaces the deprecated bundle command

packages/rspack/package.json
Otherwise there may be an error when using the wrong version of `ajv-keywords`.
=> fix(rspack): add dependency to ajv-keywords that match the version used by rspack

package.json, packages/netlify/.eslintrc.json, packages/netlify/generators.json, packages/netlify/index.ts, packages/netlify/jest.config.ts, packages/netlify/package.json, packages/netlify/project.json, packages/netlify/src/generators/preset/preset.ts, packages/netlify/src/generators/preset/schema.d.ts, packages/netlify/src/generators/preset/schema.json, packages/netlify/src/generators/serverless/schema.d.ts, packages/netlify/src/generators/serverless/schema.json, packages/netlify/src/generators/serverless/serverless.ts, packages/netlify/src/generators/serverless/severless.spec.ts, packages/netlify/src/generators/setup-serverless/files/netlify.toml__tmpl__, packages/netlify/src/generators/setup-serverless/files/src/functions/hello/hello.ts__tmpl__, packages/netlify/src/generators/setup-serverless/schema.d.ts, packages/netlify/src/generators/setup-serverless/schema.json, packages/netlify/src/generators/setup-serverless/setup-serverless.spec.ts, packages/netlify/src/generators/setup-serverless/setup-serverless.ts, packages/netlify/src/index.ts, packages/netlify/tsconfig.json, packages/netlify/tsconfig.lib.json, packages/netlify/tsconfig.spec.json, packages/netlify/utils/versions.ts, tsconfig.base.json
This PR provides an opt-in to add serverless configuration to any project or create a new project that has a server-less configuration
**New projects**
- Generate a serverless application
- Run `npx nx generate @nrwl/netlify:serverless api --platform=netlify`
- Run `npx nx run api:deploy`
**Existing Projects**
- Run `npx nx generate @nrwl/netlify:setup-serverless --project=api --platform=netlify`
- Run `npx nx run api:deploy`
This should 
1. Create a server-less application (_new projects only_) with the `netlify.toml` deploy file
2. Add the `functions/hello.ts` server-less function
3. Install `netlify-cli` which is used to deploy your node server
4. Add a deploy target to Netlify
=> feat(netlify): add @nrwl/netlify package

packages/deno/src/generators/preset/generator.ts, packages/deno/src/generators/preset/schema.d.ts, packages/deno/src/generators/preset/schema.json
This PR removes monorepo setup for `@nrwl/deno:preset` generator, so all new workspaces using the custom preset will be standalone.
Users that want to add a Deno app to their workspace can install `@nrwl/deno` and call the app generator.
=> feat(deno): only support standalone projects using the custom preset

packages/rspack/src/generators/configuration/configuration.ts, packages/rspack/src/utils/with-nx.ts
This should fix the `nest` issue.
Still needs:
```
config.externals = {
'@nestjs/common': '"@nestjs/common"',
'@nestjs/core': '"@nestjs/core"',
};
```
in `rspack.config.js`
=> fix(rspack): set externals for target node

.github/workflows/actions.yml
Currently if the PR is from a forked repo, the fetch action will fail because we're not pointing to the correct repo.
=> chore(repo): support forked repos for PRs

.github/workflows/actions.yml
Run nightly tests for catching issues with external package (such as `rspack`) that may release a breaking version. This is needed before we relax the pinned version of `@rspack/*` packages here https://github.com/nrwl/nx-labs/pull/195
Also added `lint` target since it was missing before.
=> chore(repo): add nightly tests and run lint during CI, merge, and nightly

packages/rspack/src/generators/application/application.ts, packages/rspack/src/generators/configuration/configuration.ts, packages/rspack/src/generators/configuration/schema.d.ts, packages/rspack/src/generators/configuration/schema.json, packages/rspack/src/generators/init/init.ts, packages/rspack/src/generators/init/schema.d.ts, packages/rspack/src/generators/init/schema.json, packages/rspack/src/utils/generator-utils.ts
Make the `rspack:configuration` generator work like the `vite:configuration` generator. It only accepts a specific type of executors that can be converted. It tries to infer what type of project the user is trying to convert. It allows user to specify framework to be used when converting (`react`, `web`, `nest`).
=> feat(rspack): configuration generator better ux

packages/rspack/src/executors/rspack/rspack.impl.ts
Rspack now returns the outfile name, and also accepts an output file name as input. This should solve issues with serving Nest apps, and also enhances the functionality, makes it more consistent with other builders.
=> feat(rspack): accept and return outputFileName

e2e/remix-e2e/tests/nx-remix.spec.ts, packages/remix/src/generators/action/action.impl.spec.ts, packages/remix/src/generators/action/action.impl.ts, packages/remix/src/generators/application/application.impl.ts, packages/remix/src/generators/cypress/cypress.impl.ts, packages/remix/src/generators/library/library.impl.ts, packages/remix/src/generators/library/schema.d.ts, packages/remix/src/generators/library/schema.json, packages/remix/src/generators/loader/loader.impl.spec.ts, packages/remix/src/generators/loader/loader.impl.ts, packages/remix/src/generators/meta/meta.impl.spec.ts, packages/remix/src/generators/preset/preset.impl.ts, packages/remix/src/generators/resource-route/resource-route.impl.spec.ts, packages/remix/src/generators/resource-route/resource-route.impl.ts, packages/remix/src/generators/resource-route/schema.d.ts, packages/remix/src/generators/resource-route/schema.json, packages/remix/src/generators/route/route.impl.spec.ts, packages/remix/src/generators/route/route.impl.ts, packages/remix/src/generators/route/schema.d.ts, packages/remix/src/generators/route/schema.json, packages/remix/src/generators/setup/setup.impl.ts, packages/remix/src/generators/style/style.impl.spec.ts, packages/remix/src/generators/style/style.impl.ts, packages/remix/src/migrations/update-14-5-4/update-tsconfig-and-remix-config-for-1-6-8.spec.ts, packages/remix/src/utils/remix-route-utils.ts
This PR adds some quality of life improvements to the Remix generators:
* Generators now generate code closer to the typing standards of the Remix community:
```typescript
const data = useLoaderData<typeof loader>();
// instead of
const data = useLoaderData<LoaderDataInterface>();
```
* Route params are no longer changed from camel-case to snake-case
* Route paths are checked for the very common error of an un-escaped `$`. The `$` is used in Remix for route params, but it's used for interpolation by many shells.
* The path to the Remix app directory is now resolved correctly if it has been changed in `remix.config.ts`
* Generators have been updated for better compatibility with standalone and integrated workspace
* More test and e2e coverage for Remix plugin
* Fixes the `cypress` …
=> feat(remix): quality of life improvements for Remix generators

packages/rspack/src/utils/with-nx.ts, packages/rspack/src/utils/with-react.ts, packages/rspack/src/utils/with-web.ts
We would hardcode `css/module` on all styles files (.css, .scss, etc.). This results in web-components apps (or any project that's using plain css and not css modules) not getting the styles, due to the class name mangling. Let's only pass this rule optionally, and if the project is React.
=> fix(rspack): do not force cssmodules

package.json, packages/remix/migrations.json, packages/remix/package.json, packages/remix/src/generators/cypress/cypress.impl.ts, packages/remix/src/generators/meta/lib/normalize-options.ts, packages/remix/src/generators/meta/lib/v1.impl.spec.ts, packages/remix/src/generators/meta/lib/v1.impl.ts, packages/remix/src/generators/meta/lib/v2.impl.spec.ts, packages/remix/src/generators/meta/lib/v2.impl.ts, packages/remix/src/generators/meta/meta.impl.spec.ts, packages/remix/src/generators/meta/meta.impl.ts, packages/remix/src/generators/meta/schema.d.ts, packages/remix/src/generators/meta/schema.json, packages/remix/src/generators/route/route.impl.spec.ts, packages/remix/src/utils/remix-config.ts, packages/remix/src/utils/remix-route-utils.ts, packages/remix/src/utils/versions.ts, packages/remix/tsconfig.lib.json, yarn.lock
This PR updates our Remix packages to 1.15. v2 is coming soon, so this also adds the ability to generate a `meta` function using the v2 convention, which can be enabled by the user using [future flags](https://remix.run/docs/en/1.15.0/pages/api-development-strategy#current-future-flags).
=> feat(remix): update Remix to 1.15

packages/rspack/src/utils/with-nx.ts
Rspack will use its built-in swc minifier when `optimization.minimize` is `true` and no `optimization.minimizer` is set, which is much faster than js plugin (`@rspack/plugin-minify`).
And `resolve.plugins` is not supported for now, but there is a `resolve.tsConfigPath` can do something similar.
=> fix(rspack): use built-in minifier instead

tools/scripts/publish.mjs
Just so that we can use this script with OTP enabled. It is not the most elegant way possible but does the job. We should probably look into having a similar release script as we have in the main repo (maybe just copy it over here)
=> feat: read OTP from env

packages/rspack/src/utils/with-nx.ts
There's no need to use alias and `tsconfig-paths` anymore since rspack supports it out of the box now. Also fixes a logic issue with the tsconfig path set by `withNx` function.
=> fix(rspack): use built-in tsconfig paths support

packages/deno/src/generators/serverless/__snapshots__/serverless.spec.ts.snap, packages/deno/src/generators/setup-serverless/lib/netlify.spec.ts, packages/deno/src/generators/setup-serverless/lib/netlify.ts, packages/netlify/src/generators/serverless/severless.spec.ts, packages/netlify/src/generators/setup-serverless/setup-serverless.spec.ts, packages/netlify/src/generators/setup-serverless/setup-serverless.ts
By default the site is locked so the `deploy` will fail for fresh apps
If necessary they can add this back.
=> fix(netlify): Remove --prod-if-unlocked from deploy

packages/deno/src/generators/setup-serverless/lib/netlify.spec.ts, packages/deno/src/generators/setup-serverless/lib/netlify.ts
The generated Netlify serverless function example causes linting to fail because it has an `async` modifier while there's no async code.
Also removed some of the comments about the content of the `context.geo` object as devs can look it up via the TS definitions
=> deno(fix): remove async in example to avoid lint errors

package.json
Adding some package.json scripts to be used by `nx-ecosystem-ci`, and also the `packageManager` field which is needed by the `ecosystem-ci`.
=> feat(repo): add ecosystem scripts and packageManager

packages/remix/src/generators/library/lib/add-tsconfig-entry-points.ts, packages/remix/src/generators/library/lib/index.ts, packages/remix/src/generators/library/lib/normalize-options.ts, packages/remix/src/generators/library/lib/update-buildable-config.ts, packages/remix/src/generators/library/library.impl.spec.ts, packages/remix/src/generators/library/library.impl.ts, packages/remix/src/generators/library/schema.d.ts, packages/remix/src/generators/library/schema.json, packages/remix/src/utils/project.ts
Remix Libraries should be generated with a server entrypoint in the TSConfig.
This PR does a few things:
1. Fixes generation in general -> We assumed buildable library by default and therefore tried to update the build target in the project.json -> this may not exist
2. Places buildable config updates behind a buildable flag -> this is not complete, we need to investigate buildable option further
3. The example in the schema.json shows using a directory option that does not exist -> add the directory option
4. Adds the `server.ts` file as the entrypoint for the server-only exports -> adds it to a new path in the root tsconfig file
5. Adds a `.spec.ts` file for the Library Generator -> testing isn't verbose yet, but it at least provides some confidence -> That said, we don't do anything …
=> fix(remix): library generator should create server entrypoint

packages/nx-ignore/package.json
The version was misaligned and caused issues with build.
Fixes #256
=> fix(nx-ignore): use correct @swc/helpers

e2e/remix-e2e/tests/nx-remix.spec.ts, packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap, packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/application.impl.ts, packages/remix/src/generators/application/files/integrated/package.json__tmpl__
Remix applications are currently running via scripts in package.json
Move these scripts to run-commands in project.json
Add some unit tests to the application generator to ensure it is being created as expected
=> feat(remix): move targets to project.json

e2e/remix-e2e/tests/nx-remix.spec.ts, packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap, packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/lib/normalize-options.ts, packages/remix/src/generators/application/schema.d.ts, packages/remix/src/generators/application/schema.json
We currently do not offer a `--directory` option when generating a remix application.
Offer a `--directory` option when generating a remix application.
=> feat(remix): add --directory option to application

packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap, packages/remix/src/generators/application/files/common/remix.config.js__tmpl__, packages/remix/src/index.ts, packages/remix/src/utils/create-watch-paths.spec.ts, packages/remix/src/utils/create-watch-paths.ts
This PR adds a `createWatchPaths` util function in `@nx/remix` that returns libs and packages paths relative to the app root. e.g. `['../../lib', '../../packages']`
We could narrow it down to only the libraries used by the app, but that optimization doesn't seem necessary as demonstrated here by a project with 1K libs and other 100K files under `libs`: https://github.com/jaysoo/nx-remix-large-repo. Each subsequent update takes less than a second to refresh. If we narrow down to specific lib folders, then the app will need to be restarted whenever the dep graph changes, which is not great DX.
=> feat(remix): add util to create watchPaths configuration option automatically

e2e/remix-e2e/tests/nx-remix.spec.ts, packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap, packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/application.impl.ts, packages/remix/src/generators/application/files/common/tsconfig.json__tmpl__, packages/remix/src/generators/application/lib/index.ts, packages/remix/src/generators/application/schema.d.ts, packages/remix/src/generators/application/schema.json
We do not currently offer a `--js` option for users to use JS instead of TS when generating applications
We should offer `--js` option
=> feat(remix): add --js option to application

packages/rspack/src/utils/versions.ts
Locking `@rspack/*` version to `0.1.11` [because `0.1.12` is broken](https://github.com/web-infra-dev/rspack/issues/3270).
=> fix(rspack): lock version to 0.1.11

e2e/rspack-e2e/tests/rspack.spec.ts, package.json, packages/rspack/src/executors/rspack/schema.d.ts, packages/rspack/src/executors/rspack/schema.json, packages/rspack/src/utils/with-nx.ts, yarn.lock
It's related to the ticket: https://github.com/nrwl/nx-labs/issues/219
Obs: Rspack already supports the license-webpack-plugin [Issue](https://github.com/web-infra-dev/rspack/issues/2913). It's required to upgrade the @rspack/core to get the changes implements on https://github.com/web-infra-dev/rspack/pull/3010.
In order to make the tests you can force to use the version @rspack/core:0.1.11
Update (@mandarini) : Once this PR is merged (https://github.com/nrwl/nx-labs/pull/278) we can go ahead and rebase, and then merge!
=> feat(rspack): Add extractLicenses option to rspack's project configuration

packages/remix/src/generators/route/__snapshots__/route.impl.spec.ts.snap, packages/remix/src/generators/route/route.impl.spec.ts
The test we have for route currently just checks that some text appears in the route file.
I've added a snapshot test to improve the accuracy of what gets generated and to fail quicker if a change is made.
Right now, we generate a meta, action and loader along with the route component. 
This is confirmed by the snapshot. This may become more important when we upgrade to v2
=> chore(remix): improve route test to confirm output is expected

packages/remix/src/generators/library/library.impl.spec.ts
When adding a library to a Standalone Remix Project Repo, the tsconfig paths were not being updated correctly previously.
This fix went into Nx repo itself, however, there are no assurances on the nx-labs side to ensure that this functionality remains correct moving forward.
Add a unit test to check for this behaviour.
=> chore(remix): add test to ensure the tsconfig paths are updated correctly

packages/remix/generators.json, packages/remix/src/generators/error-boundary/__snapshots__/error-boundary.impl.spec.ts.snap, packages/remix/src/generators/error-boundary/error-boundary.impl.spec.ts, packages/remix/src/generators/error-boundary/error-boundary.impl.ts, packages/remix/src/generators/error-boundary/lib/add-v1-error-boundary.ts, packages/remix/src/generators/error-boundary/lib/add-v2-error-boundary.ts, packages/remix/src/generators/error-boundary/lib/index.ts, packages/remix/src/generators/error-boundary/lib/normalize-options.ts, packages/remix/src/generators/error-boundary/schema.d.ts, packages/remix/src/generators/error-boundary/schema.json
We currently do not have an ErrorBoundary generator
Add an ErrorBoundary generator
Note: We currently have a `--version` flag to switch between the two implementations of ErrorBoundary. When this is moved to the main repo and we switch to V2 only, we can remove the v1 option.
=> feat(remix): add error boundary generator

packages/netlify/src/generators/setup-functions/setup-functions.spec.ts, packages/netlify/src/generators/setup-functions/setup-functions.ts
https://github.com/nrwl/nx-labs/pull/261 should no longer be needed since we want to lint before deploying to prod.
=> fix(netlify): Add lint pattern for functions folder

e2e/remix-e2e/tests/nx-remix.spec.ts, packages/remix/src/generators/library/lib/add-unit-testing.ts, packages/remix/src/generators/library/lib/index.ts, packages/remix/src/generators/library/lib/normalize-options.ts, packages/remix/src/generators/library/library.impl.spec.ts, packages/remix/src/generators/library/library.impl.ts, packages/remix/src/generators/library/schema.d.ts, packages/remix/src/generators/library/schema.json, packages/remix/src/generators/route/route.impl.spec.ts, packages/remix/src/utils/versions.ts
We generate Remix libs with jest for unit testing
We should offer users a choice of unit test runners between: jest, vitest, none
=> feat(remix): allow vitest to be used for libs

packages/remix/generators.json, packages/remix/package.json, packages/remix/src/generators/setup-tailwind/__snapshots__/setup-tailwind.impl.spec.ts.snap, packages/remix/src/generators/setup-tailwind/files/app/tailwind.css__tpl__, packages/remix/src/generators/setup-tailwind/files/tailwind.config.ts__tpl__, packages/remix/src/generators/setup-tailwind/lib/index.ts, packages/remix/src/generators/setup-tailwind/lib/update-remix-config.spec.ts, packages/remix/src/generators/setup-tailwind/lib/update-remix-config.ts, packages/remix/src/generators/setup-tailwind/schema.d.ts, packages/remix/src/generators/setup-tailwind/schema.json, packages/remix/src/generators/setup-tailwind/setup-tailwind.impl.spec.ts, packages/remix/src/generators/setup-tailwind/setup-tailwind.impl.ts, packages/remix/src/utils/upsert-links-function.spec.ts, packages/remix/src/utils/upsert-links-function.ts, packages/remix/src/utils/versions.ts
We currently do not have a generator that creates a TailwindCSS setup for an application
The process of doing this manually is a little involved
1. Add a `tailwind: true` property to the remix.config.js
2. Install + Init Tailwind with `npx tailwindcss init --ts` - this has to be done in the correct directory if using integrated repos
3. Add a LinksFunction to root.tsx
4. Add the tailwind.css file with the tailwind directives
We can do this in one command with a generator.
This PR adds a generator to do that.
It also adds a util function for adding or updating a LinksFunction
=> feat(remix): add setup-tailwind generator

packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/application.impl.ts, packages/remix/src/generators/application/schema.d.ts, packages/remix/src/generators/application/schema.json, packages/remix/tsconfig.spec.json
We should generate an e2e app by default for remix apps but offer users a flag to opt out
=> feat(remix): app should generate a cypress e2e project

packages/remix/src/generators/application/lib/update-vite-test-config.ts, packages/remix/src/generators/library/lib/add-unit-testing.ts, packages/remix/src/utils/testing-config-utils.ts
Refactor the testing utils file name to be more accurate as it also now contains jest logic which can be used by a future PR where app generator will allow jest to be selected as the unit test runner
=> chore(remix): refactor testing config utils

packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap, packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/application.impl.ts, packages/remix/src/generators/application/lib/index.ts, packages/remix/src/generators/application/lib/update-unit-test-config.ts, packages/remix/src/generators/application/schema.d.ts, packages/remix/src/generators/application/schema.json
Add jest support to Application generator
This puts it inline with supporting the major testing tooling we already offer for Angular, React etc
=> feat(remix): add jest support to app generator

packages/rspack/package.json
The dependency is missing making the plugin not usable.
The problem was introduced here: https://github.com/nrwl/nx-labs/pull/230
=> fix(rspack): add missing license-webpack-plugin dependency

packages/remix/src/utils/testing-config-utils.ts
Ensure Typescript is installed and available before running AST operations that require it.
Fixes #298
=> fix(remix): ensure typescript is available during workspace gen #298

packages/remix/src/index.ts
Adding the generators that have been recently created to the public api as they were missed during those PRs
=> fix(remix): export new generators from package public api

packages/remix/.eslintrc.json, packages/remix/src/utils/testing-config-utils.ts
Importing `tsquery` results in an error if `typescript` is not installed to the workspace yet. This PR ensures `typecript` is available before importing `tsquery`.
Fixes: https://github.com/nrwl/nx/issues/17762
=> fix(remix): fix error when creating new workspaces using remix preset

packages/remix/src/generators/preset/lib/normalize-options.ts, packages/remix/src/generators/preset/preset.impl.ts
This PR makes Vitest the default when running `npx create-nx-workspace --preset=@nx/remix`. User can pass `--unitTestRunner=jest` if they want to use Jest instead. 
The e2e test runner is also correctly defaulted to Cypress, just like running the app generator.
Lastly, also added `--js` flag if user choose to not use TypeScript.
=> feat(remix): set correct defaults for @nx/remix:preset to match @nx/remix:app defaults

e2e/nx-ignore-e2e/tests/nx-ignore.spec.ts
Configure commit for e2e tests, because if it's not configured then it may fail on CI with following error message:
```
Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
=> chore(nx-ignore): git config for e2e tests

packages/deno/src/graph/process-graph.ts
Within `getDenoFileInfo`, in situations where `deno info` fails it won't provide a proper JSON output, causing `buffer` to remain as an empty string and `JSON.parse(buffer)` to fail by consequence. The problem is that the current implementation wont' handle this error properly, making it generic and harder to debug.
Adding a `try ... catch` block that delegates the error object to the promise's `reject` handler ensures that this error is encapsulate into a `DenoError` object.
```sh
npx nx serve api
>  NX   Daemon process terminated and closed the connection
Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in: /Users/.../node_modules/.cache/nx/d/daemon.log
```
```
[NX Daemon Server] - …
```
=> fix(deno): provide proper error handling for process-graph

packages/remix/executors.json, packages/remix/src/executors/serve/compat.ts, packages/remix/src/executors/serve/schema.d.ts, packages/remix/src/executors/serve/schema.json, packages/remix/src/executors/serve/serve.impl.ts, packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/application.impl.ts
Add a Remix Serve Executor to allow emissions from the process that can be listened to by other processes such as Cypress.
=> feat(remix): add a serve executor

packages/rspack/src/executors/dev-server/dev-server.impl.ts, packages/rspack/src/executors/rspack/rspack.impl.ts
Rspack's internal module is not exposed since 0.3, so it would be better not use Rspack's internal module
=> chore: don't use rspack internal module

packages/remix/src/executors/build/build.impl.ts, packages/remix/src/executors/build/schema.d.ts, packages/remix/src/executors/build/schema.json
This PR fixes the Remix `build` executor to be consistent with `serve` executor -- invoking the CLI using `fork`. This change resolves and issue where postcss and other tools are using the wrong `cwd` when looking for configuration files. Tested on the `ocean` repo.
=> fix(remix): run Remix CLI instead of invoking the build programmatically

e2e/rspack-e2e/tests/rspack.spec.ts, package.json, packages/rspack/src/executors/rspack/schema.d.ts, packages/rspack/src/executors/rspack/schema.json, packages/rspack/src/plugins/generate-package-json-plugin.ts, packages/rspack/src/utils/with-nx.ts, yarn.lock
=> feat(rspack): add generatePackageJson plugin

e2e/remix-e2e/tests/nx-remix.spec.ts, packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap, packages/remix/src/generators/application/application.impl.spec.ts, packages/remix/src/generators/application/application.impl.ts, packages/remix/src/generators/application/lib/normalize-options.ts, packages/remix/src/generators/application/schema.d.ts, packages/remix/src/generators/application/schema.json
Bring Remix Appliction Generator in line with the rest of the Nx Official Plugins by implementing the new `projectNameAndRootFormat` option.
=> feat(remix): implement new projectNameAndRootFormat for application

packages/remix/src/generators/library/__snapshots__/library.impl.spec.ts.snap, packages/remix/src/generators/library/lib/add-unit-testing.ts, packages/remix/src/generators/library/lib/normalize-options.ts, packages/remix/src/generators/library/library.impl.spec.ts, packages/remix/src/generators/library/library.impl.ts, packages/remix/src/generators/library/schema.d.ts, packages/remix/src/generators/library/schema.json
Add `projectNameAndRootFormat` to Library generator for consistency
=> feat(remix): projectNameAndRootFormat for library generator

packages/nx-ignore/src/index.ts
Netlify builds seem to have broken with recent changes. `yarn` and `pnpm` aren't available during the ignore build step. 
This PR adds additional checks that `yarn` and `pnpm` are available before using them.
=> fix(nx-ignore): check that yarn/pnpm are installed before using on Netlify

packages/nx-ignore/src/index.ts
When using local plugins, `nx-ignore` also needs to install SWC to transpile `*.ts` files.
=> fix(nx-ignore): install swc to transpile local plugins

packages/nx-ignore/src/index.ts
When _any_ plugins are used, we need to also install `@nx/devkit` since it is likely used.
=> fix(nx-ignore): add @nx/devkit when plugins are used

packages/nx-ignore/src/index.ts
When using crystal-compat plugins, `nx-ignore` will fail with an error like this:
```
TypeError: plugin.startsWith is not a function
--
14:54:43.692 | at /vercel/.npm/_npx/f3975d057d897afd/node_modules/nx-ignore/src/index.js:83:133
14:54:43.692 | at Array.filter (<anonymous>)
14:54:43.692 | at findThirdPartyPlugins (/vercel/.npm/_npx/f3975d057d897afd/node_modules/nx-ignore/src/index.js:83:108)
14:54:43.692 | at main (/vercel/.npm/_npx/f3975d057d897afd/node_modules/nx-ignore/src/index.js:39:71)
14:54:43.692 | at Object.<anonymous> (/vercel/.npm/_npx/f3975d057d897afd/node_modules/nx-ignore/src/index.js:27:1)
14:54:43.693 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
14:54:43.693 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
14:54:43.693 | at …
```
=> fix(nx-ignore): support plugin object in nx.json

packages/rspack/package.json, packages/rspack/src/generators/init/init.ts, packages/rspack/src/generators/init/schema.d.ts, packages/rspack/src/generators/init/schema.json, packages/rspack/src/utils/with-react.ts
The `init` generator for `@nx/rspack` does not have the `keepExistingVersions` option which is used by `nx add`.
Add this option to allow `nx add` to invoke the init generator correctly.
=> feat(rspack): add option to keep existing versions of packages for init generator

packages/rspack/package.json
We currently depend on `ajv` and `ajv-keywords` directly in `@nx/rspack` which creates incorrect hositing pattern for package managers.
Allow hoisting to occur correctly by not depending directly on these packages. They are defined within `@rspack/dev-server` -> `webpack-dev-server-middleware` already.
=> fix(rspack): do not depend directly on ajv to allow for correct hoisting

packages/rspack/src/generators/init/init.ts, packages/rspack/src/utils/versions.ts
`@rspack/plugin-react-refresh` requires `react-refresh` but it does not install it.
Ensure `react-refresh` is installed.
=> fix(rspack): ensure react-refresh is installed

packages/nx-ignore/src/index.ts
This PR normalizes plugin paths such as `@nx/next/plugin` into package names to be installed (e.g. `@nx/next`).
=> fix(nx-ignore): normalize plugin entries into package names

e2e/nx-ignore-e2e/tests/nx-ignore.spec.ts, packages/nx-ignore/README.md, packages/nx-ignore/src/index.ts
This PR ensures that full installation is performed when using Nx plugins. There isn't a guarantee that all transient dependencies will be installed, which can lead to errors when constructing graph.
Users can pass in `--slim-install` to override this behavior.
=> feat(nx-ignore): perform full install when plugins are used and provide escape hatch

packages/nx-ignore/src/index.ts
This PR adds logging of both `stdout` and `stderr` when `execSync` fails on generating affected graph.
=> fix(nx-ignore): print stdout and stderr when affected graph cannot be generated

e2e/nx-ignore-e2e/tests/nx-ignore.spec.ts, packages/nx-ignore/README.md, packages/nx-ignore/src/index.ts
Netlify deployments currently has two problems:
1. npm packages are not installed prior to calling `npx nx-ignore`.
2. There is a three minute limit for the ignore script.
For Nx plugins that infer targets from config files, we should do a full installation to ensure packages used by config files are present. Otherwise errors like missing `@playwright/test` or `next/constants` will occur. On Vercel, this works fine because there isn't a limit to the ignore script (at least it is reasonable long). On Netlify, the three minute limit for ignore script means full installation will almost always fail.
The fix for this issue is to detect whether we're on Netlify or not (checking `NETLIFY` env var). If we're on Netlify, then perform a slim installation. And to make it more compatible with …
=> feat(nx-ignore): use slim installation on Netlify to avoid script timeout

packages/nx-ignore/README.md, packages/nx-ignore/src/index.ts
Some Nx plugins aren't in `nx.json`, for example `@nx/react`, `@nx/js`, etc. We should include all `@nx/` packages in slim install.
=> fix(nx-ignore): include all @nx/ packages since they may not be in nx.json (e.g. @nx/react/webpack-plugin)

packages/nx-ignore/src/index.ts
ts-jest and babel-jest should be installed if they exist
=> fix(nx-ignore): include ts-jest and babel-jest and other potential transforms

packages/nx-ignore/src/index.ts
It's somewhat of an edge case because Nx repo has a patched jest resolver that requires `enhanced-resolve`.
=> fix(nx-ignore): include enhanced-resolve for nx repo and potentially other repos using it

packages/nx-ignore/src/index.ts
This changes brings compatibility for Nx >= 19 since the command should be `nx graph --affected`, otherwise we cannot generate the graph.
=> fix(nx-ignore): run nx graph --affected for Nx >= 19

packages/nx-ignore/src/index.ts
The base and head SHAs must be passed to the underlying affected command.
=> fix(nx-ignore): pass base and head shas to affected projects command

packages/php/src/generators/init/init.spec.ts, packages/php/src/generators/init/init.ts, packages/php/src/phpunit/plugin/create-nodes.ts
Currently, `nx init` and `nx add @nx/php` does not configure `inputs` in `nx.json` to ignore test files. Since PHP tests are almost always under one of the following:
- tests
- Tests
- test
- test
We can ignore them from production files, which will help subsequent build and other targets.
This also helps discoverability, so users can see how to update `nx.json` to get the right fileset they need.
Unlike in the JS world, PHP is more like Java in that tests are almost always in one of the listed folders. And then the autoload is configured like this:
```
"autoload": {
"psr-4": {
"App\\": "src/"
}
},
"autoload-dev": {
"psr-4": {
"App\\Tests\\": "tests/"
}
}
```
=> feat(php): add default inputs for production files that excludes PHP tests

packages/php/src/composer/plugin/create-nodes.ts, packages/php/src/phpunit/plugin/create-nodes.ts
Some PHP projects commit their `vendor/` folder to git. This PR ensures that we don't infer them as workspace projects if that's the case (i.e. not added to `.gitignore` or `.nxignore`).
=> fix(php): ignore vendor files explicitly if they are not in gitignore
