- packages/expo/src/generators/application/files/tsconfig.app.json.template
- packages/expo/src/generators/library/library.spec.ts
- packages/expo/src/utils/add-jest.ts
fixes https://github.com/nrwl/nx/issues/10866
> fix(expo): change jest.config to be ts

- packages/nx-ignore/src/index.ts
Related Issue: https://github.com/nrwl/nx-labs/issues/82
> nx-ignore support for providing a custom base

- package.json
- yarn.lock
Fix this https://github.com/nrwl/nx-labs/security/dependabot/22
> fix(repo): update release-it

- packages/nx-ignore/src/index.ts
Refs: https://github.com/nrwl/nx-labs/issues/125
> fix(nx-ignore): use baseSha and headSha variables for print-affected

- .github/workflows/actions.yml
- e2e/gatsby-e2e/tests/gatsby.spec.ts
- e2e/nx-ignore-e2e/tests/nx-ignore.spec.ts
- e2e/remix-e2e/tests/nx-remix.spec.ts
run e2e tests in CI. 
fix nx-ignore and remix e2e tests.
disable gatsby e2e tests.
> chore(repo): add e2e to ci

- .github/workflows/actions.yml
- e2e/deno-e2e/tests/deno.spec.ts
- packages/deno/package.json
- packages/deno/src/graph/process-graph.ts
- packages/deno/src/utils/run-deno.ts
- Only process Deno projects
- Batch file handle processes
> fix(deno): improve process graph 

- packages/rspack/src/generators/configuration/configuration.ts
This PR does the following:
1. If the project has a `build` target named `build`, then it gets the `stylePreprocessorOptions` of that project
2. When generating `rspack.config.ts`, it passes the `stylePreprocessorOptions` in `withWeb` or `withReact` accordingly.
I believe that we should make sure to find the correct target (like we do in `vite`), and make sure we support conversion. Now we're just looking for `build`.
Fixes: https://github.com/nrwl/nx-labs/issues/179
> fix(rspack): handle existing stylePreprocessorOptions

- packages/rspack/src/executors/dev-server/dev-server.impl.ts
Fixes: #186
When calling `new RspackDevServer` we should pass down all the `devServer` options that the user adds in `rspack.config.ts`.
> fix(rspack): pass devServer options to devServer

- packages/rspack/src/utils/versions.ts
Don't lock on `0.1.0`. Accept latest patches when installing.
> feat(rspack): install latest patch when configuring

- packages/aws-lambda/.eslintrc.json
- packages/aws-lambda/README.md
- packages/aws-lambda/generators.json
- packages/aws-lambda/index.ts
- packages/aws-lambda/jest.config.ts
- packages/aws-lambda/package.json
- packages/aws-lambda/project.json
- packages/aws-lambda/src/generators/preset/preset.ts
- packages/aws-lambda/src/generators/preset/schema.d.ts
- packages/aws-lambda/src/generators/preset/schema.json
- packages/aws-lambda/src/generators/serverless/schema.d.ts
- packages/aws-lambda/src/generators/serverless/schema.json
- packages/aws-lambda/src/generators/serverless/serverless.ts
- packages/aws-lambda/src/generators/setup-serverless/files/README.md
- packages/aws-lambda/src/generators/setup-serverless/files/samconfig.toml__tmpl__
- packages/aws-lambda/src/generators/setup-serverless/files/src/hello-world/main.ts__tmpl__
- packages/aws-lambda/src/generators/setup-serverless/files/template.yaml__tmpl__
- packages/aws-lambda/src/generators/setup-serverless/schema.d.ts
- packages/aws-lambda/src/generators/setup-serverless/schema.json
- packages/aws-lambda/src/generators/setup-serverless/setup-serverless.spec.ts
- packages/aws-lambda/src/generators/setup-serverless/setup-serverless.ts
- packages/aws-lambda/src/utils/version.ts
- packages/aws-lambda/tsconfig.json
- packages/aws-lambda/tsconfig.lib.json
- packages/aws-lambda/tsconfig.spec.json
> feat(aws-lambda) add aws-lambda package, which adds serverless to be deployed to aws

- packages/rspack/src/utils/with-nx.ts
Using workspace libs in a standalone seem to be fine when the the tsconfig extension is like this:
```
tsconfig.app.json -> tsconfig.json -> tsconfig.base.json
```
However, once it's inside an integrated monorepo then the resolve stops working.
```
apps/demo/tsconfig.app.json -> apps/demo/tsconfig.json -> tsconfig.base.json
```
The contents all look correct, so will need to see if it's reproducible with just Rspack, not Nx and then open an issue there  if so.
> fix(rspack): add back `resolve.alias` configuration since `resolve.tsConfigPaths` seem to be incorrect in some scenarios

- packages/nx-ignore/src/index.ts
Avoid lockfile errors from breaking JSON.parse
> fix(nx-ignore): read file output of affected:graph to avoid additional warnings in stdout

- packages/aws-lambda/README.md
- packages/deno/README.md
- packages/deno/executors.json
- packages/deno/src/generators/init/schema.json
- packages/deno/src/generators/utils/imports.spec.ts
- packages/gatsby/README.md
- packages/gatsby/babel.ts
- packages/gatsby/generators.json
- packages/gatsby/package.json
- packages/gatsby/src/generators/application/application.spec.ts
- packages/gatsby/src/generators/application/files/.babelrc__tmpl__
- packages/gatsby/src/generators/application/files/gatsby-config.js__tmpl__
- packages/gatsby/src/generators/application/files/src/pages/index.none.tsx__tmpl__
- packages/gatsby/src/generators/application/lib/add-linting.ts
- packages/gatsby/src/generators/application/lib/create-application-files.helpers.ts
- packages/gatsby/src/utils/styles.ts
- packages/netlify/README.md
- packages/remix/README.md
- packages/rspack/README.md
- packages/rspack/src/generators/application/application.ts
- packages/rspack/src/generators/configuration/schema.json
- tools/scripts/readme-fragments/links.md
A few references that were missed, like README files, and `ensurePackage` in rspack plugin. Gatsby references updated as well.
> fix(misc): replace missed references to @nrwl scope

- packages-legacy/aws-lambda/tsconfig.json
- packages-legacy/deno/tsconfig.json
- packages-legacy/gatsby/tsconfig.json
- packages-legacy/netlify/tsconfig.json
- packages-legacy/remix/tsconfig.json
- packages-legacy/rspack/tsconfig.json
Need to output CJS for Nx to work, and create type defs.
> fix(misc): target commonjs for legacy packages

- packages/deno/src/generators/application/schema.json
> fix(deno): prompt for framework

- packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap
Application generator tests are broken after the watchPaths change
Fix the snapshots for application generator
> fix(remix): app generator tests

- e2e/remix-e2e/tests/nx-remix.spec.ts
- package.json
- packages/remix/src/generators/application/__snapshots__/application.impl.spec.ts.snap
- packages/remix/src/generators/application/application.impl.spec.ts
- packages/remix/src/generators/application/application.impl.ts
- packages/remix/src/generators/application/lib/index.ts
- packages/remix/src/generators/application/lib/update-vite-test-includes.ts
- packages/remix/src/generators/application/schema.d.ts
- packages/remix/src/generators/application/schema.json
- yarn.lock
Add vitest support for application
It also needs to update the include paths to match the app folder structure for remix
> feat(remix): add vitest support for apps

- packages/remix/migrations.json
- packages/remix/src/utils/versions.ts
> feat(remix): migrate remix to 1.16.1

- e2e/deno-e2e/tests/deno-integrated.spec.ts
- e2e/deno-e2e/tests/deno-standalone.spec.ts
- packages/deno/src/executors/emit/emit.impl.ts
- packages/deno/src/executors/emit/schema.d.ts
- packages/deno/src/executors/emit/schema.json
- fixes #309
- adds sourcemap option
> fix(deno): incorrect handling of deno config for emit

- e2e/rspack-e2e/tests/rspack.spec.ts
Adding this extra jest config to the child project generated by the e2e test is the only way to make the nx ecosystem ci tests pass. If this is not added, then when the e2e test tries to `test` the generated project, it throws a [jest error](https://github.com/nrwl/nx-ecosystem-ci/actions/runs/5922163332/job/16055755446).
> chore(rspack): add jest babel config to e2e

- packages/nx-ignore/src/index.ts
This PR fixes an issue caused by lockfile parsing, where the existence of `pnpm-lockfile.yaml` for example causes the Nx graph to error out when building. The issue is that we don't use the same package manager, so if pnpm is used, and `node_modules/.module.yaml` does not exist (for example), the graph will error.
The fix is to match the package manager to the one used in the repo, that way the lockfile parsing will work as expected. Also, trimming the temp `package.json` to not include things like patches, which doesn't exist at the temp location.
> fix(nx-ignore): allow nx-ignore to work without "pnpm install" to generate .module.yaml and other lockfile artifacts

- packages/aws-lambda/README.md
- packages/deno/README.md
- packages/netlify/README.md
We deprecated these packages and will no longer maintain them. Will do a follow-up PR to remove code.
> chore(misc): add deprecate notice to @nx/deno, @nx/netlify, @nx/aws-lambda

- .github/workflows/actions.yml
- README.md
- scripts/nx-release.mjs
- scripts/package.sh
- tools/scripts/publish.mjs
- tools/scripts/readme-fragments/getting-started.md
- tsconfig.base.json
I saw that some references to no longer existing packages were there, so I removed them.
> cleanup(repo): remove old packages from everywhere

- package.json
- packages/rspack/migrations.json
- packages/rspack/package.json
- packages/rspack/src/utils/versions.ts
- packages/rspack/src/utils/with-nx.ts
- yarn.lock
Update the rspack dependency versions to the latest `0.5.6`
> feat(rspack): update rspack to install the latest version

- packages/nx-ignore/src/index.ts
The `nx graph --affected` command does not work sine we don't print the affected projects or critical path like we used to. Perhaps another issue for Nx Core to address for anyone depending on this, but for now we can work around it by using `nx show projects --affected` instead.
Here is the `nx-ignore` fix working on the Nx repo (using Nx 19):
https://app.warp.dev/block/gzR1OeAdmZDeORQhkWSCBR
Here it is working on Nx 18 in a test repo:
https://app.warp.dev/block/3MX8tqMRAl8HcIdje7LKY2
Here it is working on Nx 17 in a test repo:
https://app.warp.dev/block/8sdtdBK37q6RaZHaRQxiku
Here it is working on Nx 16 in a test repo:
https://app.warp.dev/block/AjPG5Zx0xX5cp6S0GGMWBt
> fix(nx-ignore): fix handling of affected projects for Nx >= 19
